CREATE DATABASE CECSProject;

-- all tables need to be reviewed for the statment specified under the attributes in the HW document
-- figure out how to use "-" instead of "_"


-- -------------------------------------------hotel----------------------------------------------
-- DONE DONE hotelid is the primary key
--  Attribute amenities gives the amenities available at the hotel, separated by commas (for instance, “pool,restaurant,gym”)
CREATE TABLE HOTEL(
	hotelid int AUTO_INCREMENT NOT NULL,
	address varchar(100),
	manager_name varchar(50),
	number_rooms int,
	amenities varchar(200),
	PRIMARY KEY(hotelid)
);

-- -------------------------------------------room------------------------------------------------
-- DONE DONE make number and hotel_id primary key
-- DONE DONE make hotel_id foreign key to hotel
-- ?? DONE DONE maket he below trigger restrictions
	-- ?? DONE DONE I THINK type is one of ’regular’, ’extra’, ’suite’, ’business’, ’luxury’, ’family
	-- DONE DONE The occupancy is the number of people (always 1 to 5) who can sleep on a room
	-- DONE DONE Number of beds is always 1, 2 or 3
	-- DONE DONE type-beds is one of ’queen’, ’king’, ’full’
	-- DONE DONE price is a number (always a positive number, of course)
CREATE TABLE ROOM(
	number int NOT NULL,
	type varchar(10),
	occupancy decimal(1),
	number_beds decimal(1),
	type_beds varchar(100),
	price decimal(6,2),
	hotel_id int NOT NULL,
	PRIMARY KEY(number, hotel_id),
	FOREIGN KEY(hotel_id) REFERENCES HOTEL(hotelid)
);

delimiter //
CREATE TRIGGER room_tuple_correct BEFORE INSERT ON ROOM
FOR EACH ROW
BEGIN
	IF NEW.number = null
    OR NEW.type != ('regular', 'extra', 'suite', 'business', 'luxury', 'family')
    OR NEW.occupancy > 5
    OR NEW.occupancy < 1
    OR NEW.number_beds > 3
    OR NEW.number_beds < 1
    OR NEW.type_beds = ('queen', 'king', 'full')
    OR NEW.price < 0
    OR NEW.hotel_id = null
		THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT='Values dont match required standard check Room Type, Occupancy, Number of Beds,  Bed Type, or Price';
	END IF;
END;//


-- -------------------------------------------customer----------------------------------------------
-- DONE DONE cust-id is the primary key and
-- DONE DONE should be generated by the system
-- DONE DONE status is one ’gold’, ’silver’, ’business’.
CREATE TABLE CUSTOMER(
	cust_id int AUTO_INCREMENT NOT NULL,
	name varchar(50),
	street varchar(50),
	city varchar(50),
	zip varchar(15),
	status varchar(50),
	PRIMARY KEY(cust_id)
);

CREATE TRIGGER cust_type BEFORE INSERT ON CCUSTOMER
FOR EACH ROW
BEGIN
	IF NEW.status != ('gold', 'silver', 'business')
		THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT='Status is not equal to "gold", "silver" or "business"';
	END IF;
END;//


-- -------------------------------------------reservation----------------------------------------------
-- DONE DONE choose a primary key
CREATE TABLE RESERVATION(
	hotelid int,
	cust_id int,
	room_number int,
	begin_date date,
	end_date date,
	credit_card_number varchar(25),
	exp_date date,
	PRIMARY KEY(hotelid, cust_id, room_number, begin_date)
);



CREATE TABLE REVENUE(
	hotelid int,
    total float,
    FOREIGN KEY
);

CREATE PROCEDURE Occupancy(IN hotelID , IN )

-- -------------------------------------------insert data----------------------------------------------
INSERT INTO
	HOTEL(address, manager_name, number_rooms, amenities)
VALUES
	('123 spur ln, lousville, ky 40561', 'tom miller', 25,'pool,gym,dinner' ),
    ('1776 librty st, st. louis, ms 84301', 'Brit lopez', 100, 'gym,dinner,bar,water park'),
    ('762 1st st, chicago, il 60771', 'william smith', 240, 'parking,gym,computer lab'),
    ('736 willow way, new york, ny 20932', 'shela mcbride', 300, 'parking,lounge,gym'),
    ('83839, columbus st, kansas city, ms 40901', 50, 'parking,gym');
    
INSERT INTO
	ROOM(number, type, occupancy, number_beds, type_beds, price, hotel_id)
VALUES
	(25, 'regular', 2, 1, 'queen', 125.50, 1),
    (105, 'extra', 4, 2, 'king', 199.95,2 ),
    (301, 'business', 1, 1, 'full', 203.67, 3),
    (215, 'suite', 5, 3, 'king', 695.99, 4),
    (15, 'regular', 1, 1, 'full', 80.98, 5);
    
INSERT INTO
	CUSTOMER(name, street, city, zip, status)
VALUES
	('bob saget', '123 parkview dr', 'chicago', 60415, 'gold'),
    ('bill oniel', '5468 skyline dr', 'lexington', 40987, 'silver'),
    ('katie thomas', '786 colins st', 'hinswood', 90172, 'buisness'),
    ('luaren shoe', '197 fairfax rd', 'shelbyville', 49821, 'gold'),
    ('roger woods', '871 woods dr', 'hidden grove', 30981, 'silver');
    
INSERT INTO
	RESERVATION(hotelid, cust_id, room_number, begin_date, end_date, credit_card_number, exp_date)
VALUES
	(1,1,25, '2022-04-05', '2022-04-10', '1234-2345-3456-4567', '2025-06-01'),
    (2,2,105,'2022-05-12', '2022-5-21', '9087-8976-7865-6754', '2023-03-01'),
    (3,3,301, '2022-06-08', '2022-06-15', '1029-2938-3847-4756', '2022-10-01'),
    (4,4,215, '2022-10-12', '2022-10-20', '1234-5678-9012-3456', '2028-02-01'),
    (5,5,15, '2022-12-23', '2023-01-02', '0987-9876-8765-7654', '2030-05-01');
	
    
    

